const studentData = [
  {
    _id: 1,
    name: "Jenna Smith",
    age: 20,
    course: "Computer Science",
  },
  {
    _id: 2,
    name: "Jacob Johnson",
    age: 19,
    course: "Mechanical Engineering",
  },
  {
    _id: 3,
    name: "Emily Davis",
    age: 21,
    course: "Psychology",
  },
  {
    _id: 4,
    name: "Ethan Wilson",
    age: 22,
    course: "Business Administration",
  },
  {
    _id: 5,
    name: "Avery Martinez",
    age: 18,
    course: "Biology",
  },
  {
    _id: 6,
    name: "Alexander Rodriguez",
    age: 20,
    course: "Electrical Engineering",
  },
  {
    _id: 7,
    name: "Isabella Hernandez",
    age: 19,
    course: "Journalism",
  },
  {
    _id: 8,
    name: "Benjamin Lee",
    age: 21,
    course: "Chemistry",
  },
  {
    _id: 9,
    name: "Sophia Garcia",
    age: 20,
    course: "Computer Science",
  },
  {
    _id: 10,
    name: "William Brown",
    age: 22,
    course: "Mechanical Engineering",
  },
  {
    id: 11,
    name: "Alexis Green",
    age: 19,
    course: "Computer Science",
  },
  {
    id: 12,
    name: "Brandon Lee",
    age: 20,
    course: "Engineering",
  },
  {
    id: 13,
    name: "Cameron Smith",
    age: 18,
    course: "Psychology",
  },
  {
    id: 14,
    name: "Dylan Patel",
    age: 22,
    course: "Business",
  },
  {
    id: 15,
    name: "Emily Chen",
    age: 21,
    course: "English",
  },
  {
    id: 16,
    name: "Fiona Zhang",
    age: 19,
    course: "Art History",
  },
  {
    id: 17,
    name: "Gavin Davis",
    age: 20,
    course: "Mathematics",
  },
  {
    id: 18,
    name: "Hailey Kim",
    age: 18,
    course: "Biology",
  },
  {
    id: 19,
    name: "Isabelle Lee",
    age: 22,
    course: "Chemistry",
  },
  {
    id: 20,
    name: "Jack Brown",
    age: 21,
    course: "History",
  },
  {
    id: 21,
    name: "Katherine Wu",
    age: 19,
    course: "Sociology",
  },
  {
    id: 22,
    name: "Liam Jones",
    age: 20,
    course: "Political Science",
  },
  {
    id: 23,
    name: "Megan Lee",
    age: 18,
    course: "Physics",
  },
  {
    id: 24,
    name: "Nathan Kim",
    age: 22,
    course: "Music",
  },
  {
    id: 25,
    name: "Olivia Zhang",
    age: 21,
    course: "French",
  },
  {
    id: 26,
    name: "Peter Brown",
    age: 19,
    course: "Spanish",
  },
  {
    id: 27,
    name: "Quinn Davis",
    age: 20,
    course: "German",
  },
  {
    id: 28,
    name: "Rachel Lee",
    age: 18,
    course: "Chinese",
  },
  {
    id: 29,
    name: "Samuel Kim",
    age: 22,
    course: "Japanese",
  },
  {
    id: 30,
    name: "Tiffany Chen",
    age: 21,
    course: "Korean",
  },
];

module.exports = { studentData };
